export const mockNetworkData = {
    nodes: [
        { id: '1', name: 'APOE', score: 0.98, status: 'known', chromosome: '19', degree: 156 },
        { id: '2', name: 'BIN1', score: 0.95, status: 'known', chromosome: '2', degree: 89 },
        { id: '3', name: 'ABCA7', score: 0.92, status: 'novel', chromosome: '19', degree: 67 },
        { id: '4', name: 'CLU', score: 0.89, status: 'known', chromosome: '8', degree: 78 },
        { id: '5', name: 'PICALM', score: 0.87, status: 'known', chromosome: '11', degree: 92 },
        { id: '6', name: 'SORL1', score: 0.85, status: 'novel', chromosome: '11', degree: 45 },
        { id: '7', name: 'CR1', score: 0.82, status: 'known', chromosome: '1', degree: 34 },
        { id: '8', name: 'MS4A6A', score: 0.80, status: 'novel', chromosome: '11', degree: 28 },
        { id: '9', name: 'CD2AP', score: 0.78, status: 'known', chromosome: '6', degree: 41 },
        { id: '10', name: 'EPHA1', score: 0.76, status: 'novel', chromosome: '7', degree: 23 },
        { id: '11', name: 'TREM2', score: 0.74, status: 'known', chromosome: '6', degree: 52 },
        { id: '12', name: 'CD33', score: 0.72, status: 'known', chromosome: '19', degree: 38 },
    ],
    links: [
        { source: '1', target: '2', weight: 0.9 },
        { source: '1', target: '3', weight: 0.7 },
        { source: '1', target: '4', weight: 0.8 },
        { source: '2', target: '5', weight: 0.6 },
        { source: '2', target: '6', weight: 0.5 },
        { source: '3', target: '7', weight: 0.4 },
        { source: '3', target: '8', weight: 0.3 },
        { source: '4', target: '9', weight: 0.6 },
        { source: '4', target: '10', weight: 0.5 },
        { source: '5', target: '11', weight: 0.7 },
        { source: '5', target: '12', weight: 0.6 },
        { source: '6', target: '1', weight: 0.4 },
        { source: '7', target: '2', weight: 0.3 },
        { source: '8', target: '3', weight: 0.5 },
        { source: '9', target: '4', weight: 0.4 },
        { source: '10', target: '5', weight: 0.3 },
        { source: '11', target: '6', weight: 0.2 },
        { source: '12', target: '7', weight: 0.3 },
    ]
}